"""Initial schema with 7 core tables

Revision ID: 426332235da3
Revises: 
Create Date: 2025-10-30 15:51:48.198885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426332235da3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'year', name='uq_data_year')
    )
    op.create_index(op.f('ix_data_years_source'), 'data_years', ['source'], unique=False)
    op.create_table('geographies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geography_level', sa.String(length=20), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('state_abbr', sa.String(length=2), nullable=True),
    sa.Column('county_code', sa.String(length=3), nullable=True),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('tract_code', sa.String(length=6), nullable=True),
    sa.Column('tract_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("geography_level IN ('state', 'county', 'tract', 'tribal')", name='check_geography_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geographies_state_county', 'geographies', ['state_code', 'county_code'], unique=False)
    op.create_index(op.f('ix_geographies_geo_id'), 'geographies', ['geo_id'], unique=True)
    op.create_index(op.f('ix_geographies_geography_level'), 'geographies', ['geography_level'], unique=False)
    op.create_index(op.f('ix_geographies_state_code'), 'geographies', ['state_code'], unique=False)
    op.create_table('reference_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('function', sa.String(length=50), nullable=False),
    sa.Column('numerator', sa.Text(), nullable=True),
    sa.Column('denominator', sa.Text(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_2023', sa.Integer(), nullable=True),
    sa.Column('year_source', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reverse_polarity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("function IN ('divide', 'max', 'mean', 'divide_scalar', 'reverse_divide')", name='check_function'),
    sa.CheckConstraint("source IN ('ACS', 'CBP', 'EAVS', 'ARDA', 'POP')", name='check_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name')
    )
    op.create_index(op.f('ix_reference_indicators_is_active'), 'reference_indicators', ['is_active'], unique=False)
    op.create_index(op.f('ix_reference_indicators_source'), 'reference_indicators', ['source'], unique=False)
    op.create_table('aggregate_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('bin_class', sa.Integer(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('economic_score', sa.Float(), nullable=True),
    sa.Column('social_score', sa.Float(), nullable=True),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('num_indicators_used', sa.Integer(), nullable=True),
    sa.Column('num_indicators_missing', sa.Integer(), nullable=True),
    sa.Column('imputation_rate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('bin_class BETWEEN 1 AND 7', name='check_bin_class'),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geography_id', 'year', name='uq_aggregate')
    )
    op.create_index(op.f('ix_aggregate_indicators_bin_class'), 'aggregate_indicators', ['bin_class'], unique=False)
    op.create_index(op.f('ix_aggregate_indicators_geography_id'), 'aggregate_indicators', ['geography_id'], unique=False)
    op.create_index(op.f('ix_aggregate_indicators_percentile'), 'aggregate_indicators', ['percentile'], unique=False)
    op.create_index(op.f('ix_aggregate_indicators_year'), 'aggregate_indicators', ['year'], unique=False)
    op.create_table('indicator_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['reference_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_metadata_indicator_id'), 'indicator_metadata', ['indicator_id'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_clean', sa.Boolean(), nullable=False),
    sa.Column('is_imputed', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['reference_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geography_id', 'indicator_id', 'year', name='uq_indicator')
    )
    op.create_index('idx_indicators_composite', 'indicators', ['geography_id', 'indicator_id', 'year'], unique=False)
    op.create_index(op.f('ix_indicators_geography_id'), 'indicators', ['geography_id'], unique=False)
    op.create_index(op.f('ix_indicators_indicator_id'), 'indicators', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_indicators_year'), 'indicators', ['year'], unique=False)
    op.create_table('source_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_imputed', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['reference_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geography_id', 'indicator_id', 'column_name', 'year', name='uq_source_data')
    )
    op.create_index('idx_source_data_composite', 'source_data', ['geography_id', 'indicator_id', 'year'], unique=False)
    op.create_index(op.f('ix_source_data_geography_id'), 'source_data', ['geography_id'], unique=False)
    op.create_index(op.f('ix_source_data_indicator_id'), 'source_data', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_source_data_year'), 'source_data', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_data_year'), table_name='source_data')
    op.drop_index(op.f('ix_source_data_indicator_id'), table_name='source_data')
    op.drop_index(op.f('ix_source_data_geography_id'), table_name='source_data')
    op.drop_index('idx_source_data_composite', table_name='source_data')
    op.drop_table('source_data')
    op.drop_index(op.f('ix_indicators_year'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_indicator_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_geography_id'), table_name='indicators')
    op.drop_index('idx_indicators_composite', table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_indicator_metadata_indicator_id'), table_name='indicator_metadata')
    op.drop_table('indicator_metadata')
    op.drop_index(op.f('ix_aggregate_indicators_year'), table_name='aggregate_indicators')
    op.drop_index(op.f('ix_aggregate_indicators_percentile'), table_name='aggregate_indicators')
    op.drop_index(op.f('ix_aggregate_indicators_geography_id'), table_name='aggregate_indicators')
    op.drop_index(op.f('ix_aggregate_indicators_bin_class'), table_name='aggregate_indicators')
    op.drop_table('aggregate_indicators')
    op.drop_index(op.f('ix_reference_indicators_source'), table_name='reference_indicators')
    op.drop_index(op.f('ix_reference_indicators_is_active'), table_name='reference_indicators')
    op.drop_table('reference_indicators')
    op.drop_index(op.f('ix_geographies_state_code'), table_name='geographies')
    op.drop_index(op.f('ix_geographies_geography_level'), table_name='geographies')
    op.drop_index(op.f('ix_geographies_geo_id'), table_name='geographies')
    op.drop_index('idx_geographies_state_county', table_name='geographies')
    op.drop_table('geographies')
    op.drop_index(op.f('ix_data_years_source'), table_name='data_years')
    op.drop_table('data_years')
    # ### end Alembic commands ###
